version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: ez-money-tracker-backend
    ports:
      - "3000:3000"
    networks:
      - ez-money-network

networks:
  ez-money-network:
    name: ez-money-network
    driver: bridge
    internal: true
